### ISSUE TITLE
Bower home page comments/issues

### ISSUE THREAD

**Issue by gwideman** [bower/bower.github.io#105]
It's a great service to the developer community if tool originators present, up front, a concise and clear summary of what their tool is and does, so developers can quickly assess whether it's relevant to their field of work, and whether to invest further time learning it.

I think the Bower home page http://bower.io/ could use some refinement to that end.  Here's a blow by blow commentary on me trying to get traction on what it says currently:

**Bower A package manager for the web**

Nice hook, but takes in pretty broad possibilities. We see that Bower has something to do with package management, and something to do with the web, which is a vast scope. We'll be needing more specifics...

**Web sites are made of lots of things — frameworks, libraries, assets, utilities, and rainbows.**

This description fits lots of items that run on the server, and on the browser; does Bower deal with all these? Is this saying Bower can "manage" any of Django, MySQL, jquery, or angular (as examples). 

**Bower manages all these things for you.**

Well, it says "all", but I'm skeptical. From other reading, I'm pretty sure Bower actually doesn't manage things that run on the server, but perhaps I'm wrong. But now, what is the scope of "manage"?

**Bower works by fetching and installing packages from all over, taking care of hunting, finding, downloading, and saving the stuff you’re looking for.**

Again, Bower claims to install, but "hunting, finding, downloading, saving" doesn't include "configuring". So still not sure what "install" means here.

From other reading, I get the impression that Bower doesn't have features to install anything to run locally. Instead, it marshals files ready for the server to deliver them to _clients_, which is where they actually run, or appear, etc. Maybe in some sphere of web development, that's called "installing", but readers with broader experience might not know that this is the limited definition intended.

And what is the scope of "all over"?

**Bower keeps track of these packages in a manifest file, bower.json.**  So.... that's like a repo database or something? And there's just one bower.json for all packages?

**How you use packages is up to you.** This is meaningless as exposition of Bower. Clearly it's only "up to me" to choose among things that Bower facilitates. Which is what I'm here to find out, and was hoping that a sentence right about now would tell me.

**Bower provides hooks to facilitate using packages in your tools and workflows.**  The hooks are for using the packages? Or is this trying to say that Bower has an API for using Bower to perform package-related tasks?

**Bower is optimized for the front-end.**  Does this mean that sometimes Bower can be used for "installing" back-end things, but mostly it's for "installing" front-end components? Again, I'm pretty sure that Bower is for preparing delivery _only_ of front-end components. So the "optimized" claim doesn't seem to add to the discussion, and only makes a muddled suggestion that maybe there are other less-optimized uses.

**Bower uses a flat dependency tree, requiring only one version for each package,** Does "flat dependency tree" bear somehow on "one version per package"? Or is this a non-sequitur? What does "flat dependency tree" even mean? 

**reducing page load to a minimum.**  Possibly "page load _time_"?

==============
**Install Bower  
Bower is a command line utility. Install it with npm.**   OK

**npm install -g bower

Bower requires Node and npm and Git.**  These two lines are in reverse order that they are needed.

=============
**Getting started 
Install packages  
Install packages with bower install. Bower installs packages to bower_components/.**

So, if components are "installed" to bower_components/ that suggests that "install" does not mean install for local use, right? So we infer that Bower's purpose is to gather files for delivery to the browser, and not at all for local use. But readers shouldn't have to reverse engineer this understanding, if indeed it's even true.

**bower install <package>  A package can be a GitHub shorthand, a Git endpoint, a URL, and more. Read more about bower install**  

This is likely supposed to say that the argument <package> can be any of those things, not that packages themselves can be these things.

**Search packages  
Search Bower packages and find the registered package names for your favorite projects.**  

This seems confusing. Earlier the narrative says Bower can get stuff from "all over". Yet here it introduces "Bower packages". Does Bower require that candidate packages be pre-cooked in some Bower-specific way? I'm pretty sure not, but then what does this mean?  

**Save packages Save your packages to bower.json with bower init.**

Pretty sure that the packages are not saved to bower.json. I suspect only references to the package are saved to bower.json, while the packages themselves remain in bower_components. But, that's a guess.

============
**Use packages  
How you use packages is up to you.**

Again, this is meaningless as exposition of Bower, and simply frustrates anyone who doesn't already know what Bower does.

**Use Bower together with Grunt, RequireJS, Yeoman, and lots of other tools or build your own workflow with the API.**  

It's useful to know the ecosystem that Bower might work with, and it would be even better if the sentence let us know whether Bower would play a subsidiary role or a supervisory role to these other tools.

================
There you have it. There's a lot of ambiguity which I think could be ironed out to very good effect.

**Comment by desandro** [comment]
Thanks for going into depth here. I appreciate the point-by-point analysis and your many insights. I feel we may not see eye to eye on style. I see the goal of the homepage to be like marketing. It doesn't need to perfectly communicate what Bower is or how it works, it only needs to help reassure the reader to take the next step and try it out. The content should be personable, concise, with little jargon. I prefer to optimize for brevity over specificity. Confronting lots of explanatory text can be intimidating, and can scare away users.

I'll mull over your suggestions a bit more and keep this issue open for further discussion.

**Comment by JudeRosario** [comment]
Here is my viewpoint on the subject, after working with a bunch of Tech teams in both the startup and enterprise spaces. 

What someone wants when they visit a project page is to quickly find out 

> What can this project do for me now ? 
> Can it help me in future projects ? 

I think bower is a great tool and a boon to the community, I disagree with @desandro here when he says the focus is marketing or getting people to try WITHOUT clearly telling them how it benefits them / their project / or their company. I do agree when he says don't flood users with a ton of information. 

The current homepage does not do justice to the awesome project. Its neither here nor there, we need a better introductory writeup, less noise (like the twitter handle) and a usage guide a little more detailed. 

I have a Tech/API docs writing background. Can contribute a couple of hours to this project. Let me know where its needed most 

Cheers

**Comment by kevdez** [comment]
I would agree that the main page's wording can use some changes on its introduction, while also keeping a concise and marketable design.

*What is bower? A package manager for the web that you get from npm. What is npm? A package manager you can get with node. What is..."* (We really need a main page that explains itself better to the users.)

To set the stage, I would personally mention that modern web development uses a wide variety of tools on top of the bare HTML+CSS+JS, and that keeping track of all the additional modern tools/libraries/frameworks can get unmaintainable once you add things like Bootstrap, jQuery, jQuery-UI, Angular, etc. Not to mention keeping track of all the exponential combinations of versions between each tool if you require a specific version.

My other personal suggestions would be to include **concrete real-world use cases**, for example when a user wants to download the official Angular 1.1.X instead of 1.4.X or even a bleeding edge 2.X.X. I would also include that Bower allows users to neatly manage their **static** framework/library/utility files during development. I can't find a single mention of "static files" anywhere in the page and I don't think Bower deals with anything dynamic, unless there's some special task-running, file-changing stuff I don't know about besides updating/downgrading things. 

Also, @gwideman really brought to light how buzz words like "flat dependency tree" cause more confusion than explanation. When I think of "flat dependency tree" I think of "a list of dependencies", because is it really a tree if it's only got a root level and one level for children dependencies? I also don't want to get too much into semantics, so let's take the nodejs.org main site, as another example: 

"*Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient*" to where most people will answer "Yeah... okay. So is it a compiler or an interpreter?"

**Comment by tejgop** [comment]
We should improve the wording, but I don't see how AngularJS will be useful in this website.

**Comment by tejgop** [comment]
On second thoughts, the idea of putting angularJS on the website dosn't seem so bad. I'm working on it and I'll send a PR soon.

**Comment by kevdez** [comment]
I wasn't suggesting Angular nor any other internal web design choices. This conversation is more about the text content and the critique behind the current bower introduction. I was suggesting having some examples that lay out different use cases.

The intro's "Getting Started" basically tells you how to install packages, but it doesn't really bridge the gap as to *why* a user might want to do that.

We already have a few like "bower install jquery". How about 

    # for a specific version:
    bower install jquery#1.10

and 

    # for two versions on the same project
    bower install jquery-modern=jquery#2 jquery-deprecated=jquery#1

Replace jquery with angular, and you have a similar example. I wasn't suggesting Angular.

**Comment by desandro** [comment]
I appreciate the discussion, but I feel this context of this issue is a bit too broad. If you do have suggestions about copy, people open a separate issue or Pull request so we can go over in detail.
