### ISSUE TITLE
Code font on GNU/Linux

### ISSUE THREAD

**Issue by m3hr** [bower/bower.github.io#107]
The code font on bower's homepage has the following CSS:
`pre, code {
    font-family: Consolas,Menlo,Courier,monospace;
}`
GNU/Linux users tend not to have Consolas (primarily Windows) or Menlo (primarily OS X)  but do have Courier, but Courier is really ugly for code, both in my opinion and the opinion of many people that work with code. I think it would be better without the "Courier" and to leave `monospace` or replace it with a nicer font that generally comes with default GNU/Linux distributions, like Terminus or something. I was just browsing the site and this really stuck out to me lol. 

Thanks!

**Comment by sindresorhus** [comment]
Sure, PR welcome ;)
