### ISSUE TITLE
Document how to update registered repos.

### ISSUE THREAD

**Issue by inf3rno** [bower/bower.github.io#123]
By npm it is evident that you have to use `npm publish` if you have a new version of the repo. By bower the documentation tells you only to register the repo with `bower register` and that's all. There is nothing about how to update by a new version, or whether it happens automatically.

**Comment by MikaAK** [comment]
It seems to happen automatically (at least it did for a new package I kept updating today) though for some reason it's out of date on this package [thaw.js](https://github.com/robertleeplummerjr/thaw.js/blob/master/bower.json) even though the `bower.json` is updated

**Comment by inf3rno** [comment]
@MikaAK You have to use semver tags: http://stackoverflow.com/questions/28782108/is-bower-auto-updating-itself-from-github it does not do automatically, and I think it won't be affected by version in bower.json either.
