### ISSUE TITLE
License of the brand logo and colors

### ISSUE THREAD

**Issue by htanjo** [bower/bower.github.io#124]
This is not an issue, but a question.

I'm developing [bower-browser](https://github.com/rakuten-frontend/bower-browser), that is a browser-based frontend of Bower.
Now I'm planning to update its visual design.

May I use the [brand logo and colors](http://bower.io/docs/about/#brand) in my app?
Is it CC-BY as written in [package.json](https://github.com/bower/bower.github.io/blob/master/package.json#L20)?

Thanks.

**Comment by caniszczyk** [comment]
Yes, it's CC-BY

**Comment by htanjo** [comment]
Thank you! :smile:
