### ISSUE TITLE
Registration documentation clairification

### ISSUE THREAD

**Issue by blakemcbride** [bower/bower.github.io#126]
Greetings,

I am trying to register a bower library but I am having unnecessary difficulty due to the documentation.  My problems with is with the "Register" section of http://bower.io/docs/creating-packages  The sentence:

"There must be a valid manifest JSON in the current working directory."

Does "manifest JSON" mean "bower.json"?

Does "current working directory" mean "root of your repository"?

If so, why don't you say:

"There must be a valid manifest JSON file named 'bower.json' in the root of your repository."

Thanks.

Blake

**Comment by balexandre** [comment]
`manifest JSON`

`manifest` [wikipedia](https://en.wikipedia.org/wiki/Manifest_file) says it all, but you can even take it further and look to other manifest descriptions:

> The manifest is a special file that can contain information about the files packaged.... By tailoring this "meta" information that the manifest contains, you enable the (...) file to serve a variety of purposes.

`JSON` would be the `.json` part.

as we're in the context of the Bowe application, the manifest file is and always will be the `bower.json` file

I really don't think the text should be edited... it's very self explanatory.

**Comment by blakemcbride** [comment]
Okay.  Just providing feedback on how it is confusing to someone who doesn't already know the answer.  (And from someone with 30+ years Unix experience, CWD is not the same as root of the application.)  Whatever.
