### ISSUE TITLE
Bower.io search doesn't work - pretends to be a teapot

### ISSUE THREAD

**Issue by sheershoff** [bower/bower.github.io#127]
((http://dl2.joxi.net/drive/0007/0189/495805/150330/ec12729cf4.jpg))

```
Failed to load resource: the server responded with a status of 418 (I'm a teapot)
bower.io/:1 XMLHttpRequest cannot load https://bower-component-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://bower.io' is therefore not allowed access. The response had HTTP status code 418.
```

**Comment by samccone** [comment]
hi @sheershoff 

this is 
https://github.com/bower/search-server

https://github.com/bower/search-server/issues/18
https://github.com/bower/search/issues/67
https://github.com/bower/search/issues/59


More explicitly 
https://github.com/bower/search/issues/67#issuecomment-87499243

Thanks for raising this, we are aware of the issue :)
