### ISSUE TITLE
I have created a bower component, but it is not showing in the list.

### ISSUE THREAD

**Issue by rajeshwar-fissionhq** [bower/bower.github.io#129]
I have created a bower component `ionic-timepicker`. I am able to installl with `bower install ionic-timepicker`. But when i try to search the same component at http://bower.io/search/ i am unable to see my component. Are there any reasons for this or do i need to do any thing more than registering for a component?

**Comment by desandro** [comment]
Looks like it's now on there http://bower.io/search/?q=ionic-time You have to wait a couple hours before your registered package shows on the Bower package search
