### ISSUE TITLE
exception in get-size.js in Firefox 37.0.1 leaves bounded box on screen

### ISSUE THREAD

**Issue by lintondf** [bower/bower.github.io#132]
Adding a try/catch and checking for null (maybe overkill) fixes the problem

  var body = document.body || document.documentElement;
  body.appendChild( div );
  try {
  	var style = getStyle( div );

  	isBoxSizeOuter = (style) ? getStyleSize( style.width ) === 200 : 0;
  } catch (err) {
  	isBoxSizeOuter = 0;
  }
  body.removeChild( div );

**Comment by desandro** [comment]
I was not able to reproduce this error. Can you put together a reduced test case in CodePen or jsFiddle?

**Comment by lintondf** [comment]
I don't think so.  I happened using Raneto served via Heroku. Raneto embeds
masonry.pkgd.min.js which has a minified version of get-size.js.  I had to
use the console on Firefox and load a reformated version
of masonry.pkgd.min.js to find the failing line and test the protections.

You may not want the try/catch, but the if null test seem like good
practice anyway.

**Comment by desandro** [comment]
Just realized this issue was opened in `bower.github.io` repo. Open new issue in [`get-size`](https://github.com/desandro/get-size)
