### ISSUE TITLE
Please add resolutions: { } to your API documentation and it should enforce 100% compliance when used.

### ISSUE THREAD

**Issue by TMfranken** [bower/bower.github.io#134]
People who use Bower to support corporate projects with corporate clients have to support outdated browsers, we unfortunately don't live in Narnia where every company uses Google Canary for its employees.  
Bower's current condition poses challenges for people rolling back to lower versions and managing conflicting version dependencies.  The resolutions:{} block is currently not in your API documentation and it appears to not deliver enforcement of priority to versions included 100% of the time.  
This poses many challenges to companies using Bower for sophisticated deployments.  Please work to develop resolutions: {} to act as a "!NOT" clause for not installing the latest version when an outdated version is preferred; or offer another solution for this function.  Thank you

**Comment by samccone** [comment]
Hey @TMfranken thanks for raising this issue. it seems like you are reporting two different issues.

1. the lack of docs on the site
* (would you like to open a PR?) :sparkles: 
2. resolutions not functioning correctly. 
* can you open a new issue in bower documenting the issues you have found

Thanks!

**Comment by desandro** [comment]
[`resolutions` have been added to the docs](http://bower.io/docs/creating-packages/#resolutions).

![enforced](https://cloud.githubusercontent.com/assets/85566/8332077/e2a06940-1a59-11e5-8419-183ba004d702.jpg)

**Comment by samccone** [comment]
:clap:
