### ISSUE TITLE
qTip2 problems

### ISSUE THREAD

**Issue by tstar** [bower/bower.github.io#148]
Hello!

I am a beginner at bower. I apologize if my question is necessary to ask the creators of the qTip2 module.
I want to use the qTip2 module in your project. In the search form I choose the qTip2 module and get to the repository page https://github.com/qTip2/bower. This is the right repository page. But when you try to use the module in the visual studio 2015 I get the files from the repository page https://github.com/qTip2/qTip2. This page does not contain the necessary files for my project.

I did not realize it was a mistake, or the way it should be?
Who can help me solve this problem?

Thanking you in advance.

**Comment by desandro** [comment]
Sorry to hear your having trouble. Unfortunately, we won't be able to help with your implementation. I recommend reaching out to the qTip2 project for any issues using their package.
