### ISSUE TITLE
Document issues with node on Ubuntu

### ISSUE THREAD

**Issue by SalathielGenese** [bower/bower.github.io#149]
I mentioned [here](https://github.com/bower/bower/issues/1848) that ...
___
I'm so new to bower, but familiar with maven and composer and since these have nothing to do with bower, let me expose the facts.

I've been recomended bower by my teacher, by looking at his code, so find their [site](https://github.com/bower/bower/issues/bower.io). After 2 week, bower init outputed that '/usr/bin/env node' does'nt exists. So run sudo apt-get install node, but no result (errors).

I even try ((sudo)? (npm|node|nodejs)? bower init) ...

After 03 weeks (and learning nodejs and clearing cache and reinstalling all even my OS : Ubuntu 15.04), I discover [here](https://github.com/bower/bower/issues/475#issuecomment-31066364) that the problem is just sudo ln -s /usr/bin/nodejs /usr/bin/node

Please, provide a doc for true beginners, or add usefull links and comments.
___
And [this guy](https://github.com/sheerun) have [suggested](https://github.com/bower/bower/issues/1848#issuecomment-125766487) me to also write it here! I didn't know about this before.

**Comment by sheerun** [comment]
Do you want to send a pull request with explanation?

**Comment by SalathielGenese** [comment]
No

**Comment by samccone** [comment]
:cool:

**Comment by SalathielGenese** [comment]
Yes, but what's **OSS** and I'm new to [github](https://github.com) : not sure how to do this.
