### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by talgautb** [bower/bower.github.io#153]
Can you add number version of bower in main page [bower.io](http://bower.io)
always come to site compare own version with actual :)

**Comment by anubhav7495** [comment]
You can use npm for this:

     	npm outdated -g --depth=0
and npm update to update packages.

**Comment by talgautb** [comment]
@anubhav7495 yes, i know, but I told about site, not console :(

**Comment by anubhav7495** [comment]
If We can get the latest version number from the console, then why go to the site, but if you really feel like that it would be useful then we can do it.

**Comment by anubhav7495** [comment]
I will add a version badge to the bower.io soon.

**Comment by talgautb** [comment]
@anubhav7495 cool, thanks :)

**Comment by darkmorpher** [comment]
@anubhav7495 @talgautb

Seems a little too small for me

[![Bower version](https://badge.fury.io/gh/bower%2Fbower.svg)](https://badge.fury.io/gh/bower%2Fbower)

**Comment by anubhav7495** [comment]
@desandro need some feedback. what do you suggest, should i add the verson badge to the site or something else. also i cant figure out where to position the version badge.

**Comment by desandro** [comment]
Added latest release under [Install Bower](http://bower.io/#install-bower). Added `latest-release` Grunt task, using the GitHub API, so we always have the latest release.

Thanks for your contributions here!
