### ISSUE TITLE
Package search is unreliable + says no package found incorrectly before loading actual results

### ISSUE THREAD

**Issue by davidfurlong** [bower/bower.github.io#155]

**Comment by DanieleTorino** [comment]
Also, when sorting a column results are sorted by case (uppercase before lowercase).
And if the search term is an exact match it should be the first result. e.g. try searching for `jquery`. Good luck finding it...

**Comment by marcoslhc** [comment]
This issue is discussed somewhere else @davidfurlong and @DanieleTorino  https://github.com/bower/search/issues/66, https://github.com/bower/search/issues/59 and others. I'm Going to close this
