### ISSUE TITLE
Providing bower with credentials

### ISSUE THREAD

**Issue by mathikp** [bower/bower.github.io#160]
My company needs to provide bower packages to customers with credentials and custom domain. User need to install bower using custom(example http://abc.example.com/mybower.git) link and bower should ask for their unique user name and password to install. How can we achieve it? Please help.

**Comment by benschwarz** [comment]
If the packages are private github packages… you can simply use github authentication (via git) or otherwise RSA keys against a private git server.

**Comment by mathikp** [comment]
Could you please provide some more info on this? I'm not clear with your answer. If need to use github authentication, do we need to create separate github account for every customer?

Of course we need to provide private packages. We dont want to register the package to public bower registry. Customers need to use their (my company's website's credentials) credentials to use our bowers. How can we achieve this?

**Comment by sheerun** [comment]
You can create Pluggable Resolver that suits your purposes. There's no native solution right now. http://bower.io/docs/pluggable-resolvers/
