### ISSUE TITLE
Bower immediately closes

### ISSUE THREAD

**Issue by coffeetime7** [bower/bower.github.io#161]
Trying to get to grips with bower.

Have installed it on my local machine via node command line. Bower opened once, asked if i would like to share data anomalously to which i pressed 'nn' (double press by accident) and hit return.  Now when i try to open bower it immediately closes...any suggestions?

I've tried re-installing via node, no joy.  I managed to press screen print at just the right millisecond to get a flash of what bower shows before immediately closing itself...please see attached image. 

Kind regards,
![bower](https://cloud.githubusercontent.com/assets/14823765/10077762/990a909e-62d9-11e5-9768-d5e5e90befc7.jpg)

**Comment by samuelsmal** [comment]
What do you mean by "open bower"? Can you give the complete command that you enter and the result?

**Comment by marcoslhc** [comment]
@coffeetime7 did you get bower to work?

**Comment by Utsav2** [comment]
This could be a windows command prompt thing. Check [this](http://superuser.com/questions/306167/how-to-prevent-the-command-prompt-from-closing-after-execution) out. If you are facing this issue, you could open a cmd in the folder where the bower exe is, and just run 

    bower.exe

It should stay open.

**Comment by jamesxv7** [comment]
Closing issue since seems to be related to windows command and is not related to the scope of the repo. @coffeetime7 Feel confident to re open the issue if you understand to additional information is needed.
