### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by a1exus** [bower/bower.github.io#166]
I just installed bower and trying to use it and getting following error:

```
bower@1.6.5 /usr/local/lib/node_modules/bower
root@alexus:~/startbootstrap-sb-admin-2# bower install startbootstrap-sb-admin-2
/usr/bin/env: node: No such file or directory
root@alexus:~/startbootstrap-sb-admin-2#
```

is that bower or theme issue?

**Comment by anubhav7495** [comment]
This is a node related issue, this will hopefully resolve it.
    
    ln -s /usr/bin/nodejs /usr/bin/node
