### ISSUE TITLE
Moving Bower Specific Issues

### ISSUE THREAD

**Issue by pertrai1** [bower/bower.github.io#182]
@sheerun Should the issues that have been reported here that are intended for the Bower repo be moved to the Bower repo so they don't sit here? I might be wrong in that they do belong here but wanted to make sure that they are moving forward in the right repo for resolution.

**Comment by faceleg** [comment]
I would suggest to the person who raised it that they will be better served raising the issue on the relevant bower repo, then close this issue.

**Comment by sheerun** [comment]
Yes. You can move those issues by yourself too :) No need to ask persons who raised those issues.

But in the future we can close issues here and ask to raise them on bower/bower.
