### ISSUE TITLE
Homepage copy is awkward and overly cute

### ISSUE THREAD

**Issue by benschwarz** [bower/bower.github.io#183]
![](http://i.germanforblack.com/Bower_2015-11-23_09-27-23.jpg)

Originally discussed [here](https://github.com/bower/bower.github.io/commit/3f3b7623f383f5da6836c893f6a3f64d440ce3e0#commitcomment-14550455)

Tldr; What we had previously was probably too cute for my liking — now its just a bit more awkward and I'd like to see if we can come up with something better.  

Proposal: We change it to what it was before and move on. 
Or, we come up with something new. Here's a stab. 

> The web is made of lots of things — frameworks, libraries, assets and utilities. Bower helps you to install and manage front-end dependencies. 

Thoughts: Perhaps something about dependencies coming from multiple sources and authors. I think the audience is a group of people who perhaps aren't familiar with a package manager, or why you'd use one for front-end.

**Comment by pertrai1** [comment]
@benschwarz I think that if it will be changed, it will be something that is short and to the point as you have shown above.

**Comment by benschwarz** [comment]
@desandro is the branding lead here, I'd like to hear his take.
Also, happy to roll something out and improve further in more pull requests.

**Comment by pertrai1** [comment]
@benschwarz @desandro Please take a look at my pull request #181 when looking at the copy as well.

**Comment by desandro** [comment]
Let's just remove "rainbows." Adding "front-end dependencies" is jargon-y. The purpose of the tagline is  a human-readable explanation.

> Web sites are made of lots of things &mdash; frameworks, libraries, assets, and utilities. Bower manages all these things for you.

**Comment by anubhav7495** [comment]
![screenshot from 2015-11-24 00 33 29](https://cloud.githubusercontent.com/assets/10097603/11346521/1106160c-9243-11e5-927b-b892f1aa8ffc.png)

**Comment by anubhav7495** [comment]
I think this looks much cleaner and less awkward.

**Comment by anubhav7495** [comment]
@desandro If we should do something more or less, please let me know, otherwise this issue could be closed.

**Comment by pertrai1** [comment]
@desandro I have done another change with the same concept except the navigation looks different and the use of custom fonts.

![screenshot from 2015-11-23 20 28 38](https://cloud.githubusercontent.com/assets/442374/11355251/8ae9182e-9221-11e5-9358-0d277bb7a442.png)

**Comment by benschwarz** [comment]
Lets go with the @desandro copy edition —
