### ISSUE TITLE
bower.io - changelog section

### ISSUE THREAD

**Issue by darkmorpher** [bower/bower.github.io#186]
Should there be a change-log for every major version jump for bower on bower.io homepage? This could be a nice addition to #153

**Comment by mflores88** [comment]
I think it would be a really nice addition. When I download a new major version of anything, I always check the change-log for any incompatibilities and disruptive changes.

**Comment by sheerun** [comment]
We don't release major versions like ever.. :)

I think it's too much, we can just link to changelog in github repository.

**Comment by desandro** [comment]
Not a bad idea! But I find that using GitHub Releases is more functional, than trying to document it elsewhere. Integrated Issue linking. Automatic links for zip/tar downloads. Automatic links to commits.
