### ISSUE TITLE
Document how source mapping works (maybe with example?)

### ISSUE THREAD

**Issue by KatieLo** [bower/bower.github.io#195]
We could perhaps add an example or improve the explanation of how Bower makes source mapping available and what that means in the API docs (under Consuming a package) - see discussion on #194

**Comment by sheerun** [comment]
I don't get what "source mapping" is. Maybe we should remove this statement.

**Comment by BenMann** [comment]
It just shows where a certain package is located. "Name-to-path mapping" is a pretty accurate description (whereas source mapping is rather confusing IMO.. sounds like minified JS/CSS source maps).
