### ISSUE TITLE
Confusing license.

### ISSUE THREAD

**Issue by albertinad** [bower/bower.github.io#199]
The license of this project is confusing. The package.json defines CC-BY-4.0 license, where the bower.json specify MIT license. Which one is the right license?

Thanks!

**Comment by desandro** [comment]
I've been confused about how to license repos with authored content (blogs, documentation, art). I'd like for the site source code to be licensed MIT - template, HTML, JS, CSS. But the written content should be CC-BY — documentation, blog posts.

I'd say best solution is to license it all MIT, keep it consistent with bower/bower.

Related projects

+ [api.jquery.com is licensed MIT](https://github.com/jquery/api.jquery.com/blob/6f9531167072d3e39aafb32804f8cb94c1d39634/LICENSE.txt)
+ [npm/docs is licensed ISC](https://github.com/npm/docs/blob/697f1bcfa6ddfa9ba61f06551406e2c5c63cdd30/package.json)
+ [Polymer/docs doesn't have a clear license](https://github.com/Polymer/docs/tree/8bbbb9e4593919d97db1e5c57f0420cd0ac42c10)
+ [angular.io is licensed Apache 2](https://github.com/angular/angular.io/blob/452e7e7729ae2d38621c9d1039f95db34157346e/LICENSE)

**Comment by oosidat** [comment]
Interesting question @desandro - I'm fairly new to this, but could the following solution work (assuming bower wishes to separate licensing for code and content)?

http://programmers.stackexchange.com/questions/264968/can-a-single-github-repository-include-source-code-released-under-multiple-licen

What would need to happen (at least in my head) is the following:

* `package.json`, `bower.json` both have MIT as the license; a LICENSE file referencing the MIT license is placed in the root folder of the repo
* the `_data`, `_posts` and other similar (content) folders each contain a copy of the CC-BY license

Thoughts?

**Comment by echavezNS** [comment]
The MIT license is now into the `package.json`, could we close this issue? @desandro

**Comment by sheerun** [comment]
yup
