### ISSUE TITLE
--force documentation is not very helpful

### ISSUE THREAD

**Issue by hdgarrood** [bower/bower.github.io#200]
"Makes various commands more forceful" doesn't really tell me anything that I couldn't have guessed from the name.

For instance, I am wondering:
* Does it affect caching? If so, how?
* Which commands does it apply to?
* Presumably it will overwrite other files that happen to be in `bower_components`?

**Comment by sheerun** [comment]
Yes, wee need someone to read bower's source and document `--force` behavior.

Anyone, @bower/contributors ?

**Comment by dvidsilva** [comment]
I can make some today and give it a shot

**Comment by kevdez** [comment]
I'm looking at the source as well. I'll add things if I see something missing when a PR comes up.

**Comment by sheerun** [comment]
@dvidsilva @rscnt Could you complete #202 ?

**Comment by dvidsilva** [comment]
merged

**Comment by sheerun** [comment]
I meant to add missing stuff and review existing

**Comment by hdgarrood** [comment]
Wow, thanks for looking at this so quickly! :)

**Comment by kevdez** [comment]
I did an entire search on "force", filtering out the `force-latest` option and I found those 4 commands that use `--force`: install, uninstall, and register/unregister. In #202 I forgot to add `register`. Both `register` and `unregister` have the same results, just adding this in #203 for clarity. This should close the issue.
