### ISSUE TITLE
This repo has 4 branches, 3 of which are already merged. Delete?

### ISSUE THREAD

**Issue by kevdez** [bower/bower.github.io#204]
https://github.com/bower/bower.github.io/branches

These 3 other branches are 21, 43, and 94 commits behind.

Is it conventional to delete someone else's branch? Or does the creator of that branch normally do it? I mean... just minor year end cleaning. Nothing serious.

**Comment by sheerun** [comment]
For sure you can remove all branches listed in `git branch -r --merged | grep -v master | sed 's/origin\///'`

As for other branches, you need to make sure all work there is already present in master and then you can remove branch as well.

The same goes for all bower repositories.

Basically the only branches to not delete are currenly open PR branches, maybe some WIP branches, and master branch.
