### ISSUE TITLE
angular latest changing to tfeslee-temp

### ISSUE THREAD

**Issue by ConstructionFYI** [bower/bower.github.io#205]
I can't find my information on this by searching. When I go to http://bower.io/search/ after 2 seconds *angular-latest* switches to *tfeslee-temp*. This happens in Chrome and Edge. Is there a reason for this? My concern is that this may be one of those browser hijacking 'viruses', that changes links/keywords - but again, my search came up with nothing obvious so I came here. 

![image](https://cloud.githubusercontent.com/assets/14263661/12027559/4ae9ac76-ad96-11e5-993b-9090b6504d5f.png)

![image](https://cloud.githubusercontent.com/assets/14263661/12027550/3544c9c8-ad96-11e5-9ceb-3687cecb71a4.png)

**Comment by BenMann** [comment]
Don't worry about it, there's nothing bad happening in any way. The link is still the same. This is a bug on our end and I probably caused it when hotfixing the dedupe function. Looks like there's something wrong with the repoNames array. Most likely search just skips names now. Would be interesting to know if this only happens for angular-latest! https://github.com/bower/search/commit/67125e2ff22032caf46742becd448a808d0621ff

**Comment by ConstructionFYI** [comment]
Thank you.

**Comment by faceleg** [comment]
Closing due to @BenMann's calming words.
