### ISSUE TITLE
Update doc to specify that one can use env variable in bowerrc

### ISSUE THREAD

**Issue by ptitgraig** [bower/bower.github.io#208]
One can use environment variable in bowerrc. That info is not available in the doc.
```json
"storage" : {
  "packages": "/path/to/${USER}/packages"
}
```

I'm willing to add it somewhere. Any suggestion on where to place this info.
It doesn't make much sense in "Placement and order".

Maybe add a new section in the bower spec ?

**Comment by faceleg** [comment]
At first I thought, this will be easy to solve! Then I looked at the website and ... hmmm.

Need more input here @bower/contributors @bower/bower-website thoughts on where this could go?

**Comment by dvidsilva** [comment]
I think this mentions http://bower.io/docs/config/ that env variables are permited, but it doesn't mention how the syntax should be. And then when you go here https://github.com/bower/spec/blob/master/config.md it goes into more details, maybe that's a good spot to add it?

**Comment by BenMann** [comment]
agree! :+1: 
http://bower.io/docs/config/ could be more elaborate, or contain an example.

**Comment by dvidsilva** [comment]
We could move a lot of that information in the following link to that page, I'll give it a try tomorrow and create a PR

**Comment by dvidsilva** [comment]
Created a PR https://github.com/bower/bower.github.io/pull/209 adding some info to that page 

![screen shot 2016-01-14 at 12 54 02 pm](https://cloud.githubusercontent.com/assets/1588753/12337318/20551a56-babe-11e5-8fb0-0e56a45a7479.png)

**Comment by jamesxv7** [comment]
Closing as per PR #209 implementation. @ptitgraig Feel confident to re open the issue if you understand to additional clarification is needed.

**Comment by ptitgraig** [comment]
Good job !
