### ISSUE TITLE
Save packages text, seems confusing or incomplete?

### ISSUE THREAD

**Issue by jstacoder** [bower/bower.github.io#212]
Save packages

Save your packages to bower.json with `bower init`.

Seems confusing since  really it creates the file which the dependencys will be installed to, maybe this would be clearer:

Save packages

Create a bower.json file for your package with `bower init`.

Then save newly installed dependencys with `bower install NAME --save`

Thoughts?

**Comment by anubhav7495** [comment]
Yup, much more clear. Just like someone would do while using NPM.
