### ISSUE TITLE
bower install installs packages not in getting started

### ISSUE THREAD

**Issue by markmnl** [bower/bower.github.io#215]
It may seem obvious, but for a first time user the command `bower install` by itself is not explained in getting started. So for users inheriting a project with bower wonder how to install the packages.

Googling "bower install packages from bower.json" gives the first result as [Creating Packages](http://bower.io/docs/creating-packages/) which doesn't help them.

Suggested fix, sentence like: 'bower install' installs the project dependencies listed in bower.json.

(It's especially important to capture the user experience of a first time user).

**Comment by cedced19** [comment]
It's already set [here](http://bower.io/docs/api/#install) but I'm submitting a pull request.

**Comment by desandro** [comment]
PR merged

**Comment by BenMann** [comment]
I guess with that we can also close?
Feel free to re-open if not.
