### ISSUE TITLE
bower for require?!

### ISSUE THREAD

**Issue by dotku** [bower/bower.github.io#217]
I want to have a feature that I can just using bower to work with jquery/css require action, such as:

    <script>
        bower_require('jquery');
    </script>

so the jquery would be imported by CDN or using github directly maybe?! without any download or so on.

**Comment by cedced19** [comment]
You can use [debowerify](https://github.com/eugeneware/debowerify). 
I think Bower must be only a package manager.

**Comment by dotku** [comment]
@cedced19 Good to know, but it is for Node.js not for frontend development :(

**Comment by cedced19** [comment]
It is for fronted but you are right, it use node to compile.

**Comment by dotku** [comment]
@cedced19 If I'm using Java, PHP or C#, I won't be able to use it :(

**Comment by cedced19** [comment]
You can use it before deployment, you just have to build. I have no other idea maybe other can have an idea.

**Comment by kunyan** [comment]
if you want do nothing before deployment, it should be have a js lib include and replace "bower_require" to <script>
or like this


```
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('jquery', '1.3.1');
  google.setOnLoadCallback(function() {
    // do stuff
  });
</script>
```

**Comment by BenMann** [comment]
It is pretty much as @cedced19 said. There are options, but no "native" way to do this with Bower. Also note that downloads will always be part of the workflow, so you can use cached versions etc.
Hope this helps — If not, let us know!
:arrow_right: closing!
