### ISSUE TITLE
Explicit documentation regarding bower update and bower install commands

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [bower/bower.github.io#226]
Hi,

I recently came up on [this post](https://groups.google.com/forum/#!topic/twitter-bower/TXuqddaiz_8) called "What is the difference between install and update?":

> Running "bower install" in the presence of a bower.json file will install missing components, update components when the version in bower.json has changed, and prompt the user to resolve any conflicts that are not able to be resolved automatically. Running "bower update" does all of the same things, but seems to be better at conflict resolution.

The link provides details of what the OP means by "better at conflict resolution". Unfortunately the post is from 2014 and since then there was no response.

The thing here is that [the docs](http://bower.io/docs/api/#update) for `bower update` only says that the command:

> Updates installed packages to their newest version according to bower.json.

It doesn't mentions any benefits or differences between `bower install` or at least that they are equivalent (you can use only `bower update` to also install dependencies and be safe).

Can we please decide if the above makes sense and have a public definition of:
- The relationship between `bower update` and `bower install`?
- The relevant differences between `bower update` and `bower install` when using only `bower update` to install dependencies by default?

Thank you!

**Comment by Manochehrghamary** [comment]
Tanx support

**Comment by sheerun** [comment]
I've marked update command as deprecated. Its behavior was never fully specified and had many bugs. Proper semvers and "bower install" is recommended instead.
