### ISSUE TITLE
Color Accessibility Issues

### ISSUE THREAD

**Issue by longmatthewh** [bower/bower.github.io#230]
There are a decent amount of color accessibility issues throughout. 

Here are some examples of foreground and background color combinations that aren't WCAG 2.0 compliant...neither AA or AAA:
1. The title (#EF5734) and header background (#FFCC2F).
2. The blue (#00acee) link text on the left hand side with a background of white.
3. Both the blue (#00acee) and green (#2baf2b) link text in the main nav at the top with the header background (#FFCC2F)

**Comment by desandro** [comment]
Thank you for reporting this issue. I hear your concerns about the color contrast. As a color-blind designer, I see plenty of contrast in each of the cases you have pointed out. The colors differ significantly from one another in hue and lightness. I feel it's better to keep colors on brand.

**Comment by longmatthewh** [comment]
Color contrast can be an aggravating issue to deal with, especially because sometimes the "issues" don't appear to be issues at all...even to someone with a visual impairment. I'm merely offering up my observation as an open issue to state that if your goal is to be WCAG 2.0 compliant, the color contrast ratios I mentioned in this issue are not WCAG 2.0 compliant at all (there are contrast ratios defined in the guidelines). I agree that it can be especially tough to address an issue like this once you already have branding in place, which is why it's very important to keep this in mind up front. Thanks for the response, and of course feel free to close the issue if addressing this is not a priority. Cheers and thanks for Bower!
