### ISSUE TITLE
Feature Request: include asset in bower.json 

### ISSUE THREAD

**Issue by elmar-chen** [bower/bower.github.io#237]
It's common that some libaries have fonts, images and other assets as a part of their release. It would be great to keep such information in bower.json so build tools can copy only those files while building the production release.

**Comment by riyadhalnur** [comment]
@elmar-chen I think you wanted to open this issue on the actual https://github.com/bower/bower repo?

**Comment by sheerun** [comment]
You can use tools like webpack to extract used css / images. No need to declare them 2 times. DRY.
