### ISSUE TITLE
Configuration wording could be more clear

### ISSUE THREAD

**Issue by dvidsilva** [bower/bower.github.io#242]
On this page, http://bower.io/docs/config/ , is not super clear what the importance is, how to use hooks, and is missing that config can be added as a property in the bower.json.

**Comment by BenMann** [comment]
Suggested changes? 😉

**Comment by dvidsilva** [comment]
Yes sorry lol, had a crazy week, I intended to create this and close it right away but got caught up at work.

Mostly I just wanna add that .bowerrc is not required to specify configuration, and that this can be added on the bower.json.
