### ISSUE TITLE
Typo in .bowerrc documentation?

### ISSUE THREAD

**Issue by sigfriedCub1990** [bower/bower.github.io#245]
Hello, I've checked the documentation for .bowerrc and it specifies that proxy connections should be as follow:
```
{
"proxy" : "http://localhost:3128",
"https-proxy" : "https://localhost:3128"
}
```
However, this does not work for me, instead I should type `"https-proxy" : "http://localhost:3128"`, **notice**, without **https**. Hope this help. Cheers sigfried

**Comment by sheerun** [comment]
Could you send a PR with fix?
