### ISSUE TITLE
Connection times out when trying to access https://bower.io

### ISSUE THREAD

**Issue by rjgux** [bower/bower.github.io#247]
http://bower.io works fine and loads near-instantly.

https://bower.io times out 'This site cannot be reached. bower.io took too long to respond. ERR_CONNECTION_TIMED_OUT' in Chrome.

Using a Macbook Air, OS X El Capitan on a wireless connection. No firewall or anti-virus blocking the network.

Edit: Others also experiencing website offline/connection time out looking at Twitter.

**Comment by sheerun** [comment]
I've sent support ticket to github to check that cloudflare's ip addresses are whitelisted

**Comment by cjerdonek** [comment]
<img width="1248" alt="bower" src="https://cloud.githubusercontent.com/assets/355822/15943104/416680a8-2e3c-11e6-8502-65f2d5c01774.png">

**Comment by sheerun** [comment]
@cjerdonek Is it https or http version?

**Comment by cjerdonek** [comment]
https

**Comment by cjerdonek** [comment]
It's working now.

**Comment by rjgux** [comment]
Also working for me too now.

**Comment by sheerun** [comment]
I think it should be fine now
