### ISSUE TITLE
Package change: need to update package URL

### ISSUE THREAD

**Issue by uchilaka** [bower/bower.github.io#248]
Hi - I've published a package `lng-oauth-google` and I now need to change it's referenced repository URL. I've transfered the package from Bitbucket to Github, and the updated URL is: https://github.com/uchilaka/lng-oauth-google. Can you help either unregister lng-oauth-google, or update it's URL? I've also created lng-oauth-google2 with the correct URL reference (sorry for the mess!) - I'll need this unregistered as well. 

This is only published on Github as a public repository, and is used internally on my org's projects (not is use yet), and I intend to re-publish with the correct URL IF un-publishing is the easiest path to resolution, so any loss of service will only be while we sort out / update `lng-oauth-google` (from a dependency perspective). 

Thanks.

**Comment by sheerun** [comment]
('ve unregistered this package, you can register it again
