### ISSUE TITLE
bower.io search bug

### ISSUE THREAD

**Issue by bhenav** [bower/bower.github.io#250]
![image](https://cloud.githubusercontent.com/assets/14276250/16128872/18bb781e-340b-11e6-8eca-57b2bf7838d3.png)

**Comment by sheerun** [comment]
it's not a bug. there are actually such packages registered (word case counts)

**Comment by bhenav** [comment]
Have two same package name can be used?

2016-06-17 0:14 GMT+03:00 Adam Stankiewicz <notifications@github.com>:

> Closed #250 <https://github.com/bower/bower.github.io/issues/250>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bower/bower.github.io/issues/250#event-695228150>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANnWmosPl60rgNnqqSetIVVjb3XlLzsYks5qMbyagaJpZM4I3ru3>
> .
>



-- 
*Saygılarımla,*
--------------------------

*Kutbettin YAVUZ*Web Developer
Tel: 0 (507) 546 1115
http://www.kutbettin.com

**Comment by bhenav** [comment]
Okey,
I'm sorry, I did not look carefully.

2016-06-17 9:11 GMT+03:00 kutbettin yavuz <kutbettinyvz@gmail.com>:

> Have two same package name can be used?
>
> 2016-06-17 0:14 GMT+03:00 Adam Stankiewicz <notifications@github.com>:
>
>> Closed #250 <https://github.com/bower/bower.github.io/issues/250>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/bower/bower.github.io/issues/250#event-695228150>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ANnWmosPl60rgNnqqSetIVVjb3XlLzsYks5qMbyagaJpZM4I3ru3>
>> .
>>
>
>
>
> --
> *Saygılarımla,*
> --------------------------
>
> *Kutbettin YAVUZ*Web Developer
> Tel: 0 (507) 546 1115
> http://www.kutbettin.com
>



-- 
*Saygılarımla,*
--------------------------

*Kutbettin YAVUZ*Web Developer
Tel: 0 (507) 546 1115
http://www.kutbettin.com
