### ISSUE TITLE
Emojis aren't rendered properly in repository description

### ISSUE THREAD

**Issue by ZDroid** [bower/bower.github.io#254]
Emojis in repository descriptions of Bower Search are written down like this: `cookie:`. Please change it to `:cookie:`, display it as emoji or exclude it. It may be misunderstood right now.

**Comment by julmot** [comment]
@sheerun Do you think it is useful to show emojis in the Bower search? As @ZDroid mentioned we could alternatively just remove them.

**Comment by sheerun** [comment]
@ZDroid Could you provide an example to test? Not sure it's worth it. The number of packages using it is probably very low.

**Comment by ZDroid** [comment]
@sheerun I have noticed it in my repositories so far (ZDroid/mistype, ZDroid/droid), can't tell for others cause I'd have to look at many repositories. Point of Bower Search is simple -- have all core information, including the repository description, displayed properly. If my repositories information is displayed as "pencil: A simple and ...", people will think it has something to do with pencils. Do you get me?

**Comment by sheerun** [comment]
First things first, we cannot convert emojis because `pencil:` is what we receive from libraries.io

@andrew Could you debug this?

**Comment by sheerun** [comment]
https://libraries.io/api/bower-search?q=mistype

**Comment by julmot** [comment]
Ping @andrew

**Comment by andrew** [comment]
sorry about the delay, been busy releasing https://dependencyci.com/

Fixed up both mistype and droid emojis in descriptions now, the bug was fixed a long time ago, just some stale data, let me know if you see any others.

**Comment by ZDroid** [comment]
It is fine now. I'd still leave the possibility to have emojis rendered as in #255, that's a good feature.

**Comment by julmot** [comment]
@ZDroid Just reviewing this.
