### ISSUE TITLE
Search query issues

### ISSUE THREAD

**Issue by Mottie** [bower/bower.github.io#257]
I don't know when it changed, but query strings in the url are no longer working.

http://bower.io/search/?q=jquery.tablesorter

If I search for `tablesorter`, my fork, which is registered as `jquery.tablesorter`, does not show up in the results.

**Comment by julmot** [comment]
@Mottie Thanks for submitting.

Could you please tell us why the GET parameter handling is necessary for you?

@sheerun As you've initially introduced the new search page, maybe you can tell us more about this behavior?

**Comment by sheerun** [comment]
probably I omitted it when porting  from angular app. we could implement it once again

**Comment by sheerun** [comment]
As for `tablesorter`, we started matching components by prefix.. That's how @librariesio prepared endpoint for us.

**Comment by julmot** [comment]
I'd say let's wait for @Mottie's feedback. The only use case I can imagine is e.g. when someone wants to show all packages with a specific prefix (e.g. `angular-` or `datatables.net-`).

**Comment by Mottie** [comment]
Oh, I was that link in my readme. If you click on the bower badge, it takes you to the search page. It really isn't essential, but sometimes users don't read instructions and would rather click a link to see the bower package name.

**Comment by julmot** [comment]
From a usability point of view this may be helpful. Also, I didn't know the badge behavior. 
I'd say the effort to implement this is quite less (~1h), so let's work on this.

**Comment by Mottie** [comment]
Oh, I created the badge by combining a link to the search page and img.shields.io - so it may not be a typical behavior

[![Bower Version](https://img.shields.io/bower/v/jquery.tablesorter.svg)](http://bower.io/search/?q=jquery.tablesorter)

```md
[![Bower Version](https://img.shields.io/bower/v/jquery.tablesorter.svg)](http://bower.io/search/?q=jquery.tablesorter)
```

**Comment by julmot** [comment]
@Mottie Good news. This is now implemented and will be live as soon as the server cache is cleared (maximum 2h).

Cheers :beers:
