### ISSUE TITLE
Search: Reference to homepage instead of GitHub

### ISSUE THREAD

**Issue by julmot** [bower/bower.github.io#261]
Currently the search lists all results of a query with GitHub links. While this isn't a problem it might be helpful to directly link to the homepage if possible, as this often contains the actual information a user is searching for at this point.

@sheerun What do you think?

**Comment by sheerun** [comment]
maybe both?

**Comment by julmot** [comment]
How would you bring these two links into the UI?

**Comment by BenMann** [comment]
If available, we could just add it below the description like this. I think more columns are no option. In general I'm not totally against reimagining the entire search output though. :cake:

<img width="1137" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7561396/17393274/f2a2e9ee-5a22-11e6-81ee-64775f7057da.png">

**Comment by julmot** [comment]
@BenMann I don't think this brings the homepage to a more popular position. When overflying results I would click on the package name and don't read the description. I'd suggest replacing the package link with the homepage and referencing the GitHub link in a new table column containing a :octocat: (which would make it tiny).

When refactoring the search itself I'd suggest removing the author column and just adding it to the package name itself, e.g. `twbs/bootstrap`. Also I'd suggest removing the `<p>` inside the table that will be shown in mobile viewports, as this looks like a temporary hack.

**Comment by sheerun** [comment]
+1 for an icon next to the title (but I'd rather add homepage icon, as it's less popular that repository url that all bower packages have).
