### ISSUE TITLE
search box inoperable

### ISSUE THREAD

**Issue by allan-bonadio** [bower/bower.github.io#272]
steps to reproduce: 
- surf to https://bower.io/search/     (or click Search from front page)
- enter 'jquery' into the box (or any other package guaranteed to be there)
- hit return.
  expected:  list of jquery packages
  actual: no response

THere is also a JS log error:
index.js:1133 Uncaught SyntaxError: Unexpected token return

the code in question: middle line:

Headers.prototype['delete']=function(name){delete this.map[normalizeName(name)]}
Headers.prototype.get=function(name){var values=this.map[normalizeName(name)]    return values ? values[0] : null
  }

probably you guys already know this?

**Comment by julmot** [comment]
Hey @allan-bonadio,

Thanks for submitting.

Unfortunately I wasn't able to reproduce your problem in Internet Explorer 9-11 and the latest Firefox & Chrome. What browser are you using?

Anway, I've found the following issues:
- The border around the search input isn't visible in IE
![no-input-border](https://cloud.githubusercontent.com/assets/8310677/19676665/e15b50f0-9a95-11e6-83de-36137e0b6b6b.png)
- In IE9 no "old browser" message will be shown, just "there was an error"

**Comment by EricMcRay** [comment]
+1
I am using Chrome on my Macbook

**Comment by julmot** [comment]
I've just tested this in Chrome 35 (I already tested 54) and Chrome 40 under Mac OS X  10.11 and it worked. 
Also the strange thing is that index.js:1133 doesn't contain a `return` statement like mentioned. 
@EricMcRay What version are you using? Could you please clear your cache and try again?

**Comment by idelb** [comment]
+1
<img width="1266" alt="schermata 2016-10-25 alle 20 04 56" src="https://cloud.githubusercontent.com/assets/6381404/19698148/5cd9e2ca-9aee-11e6-9a2a-d59440d0cdc4.png">


Headers.prototype.get=function(name){var values=this.map[normalizeName(name)] return values ? values[0] : null
}

You don't need to reproduce the error, it is clear that the semicolon is missing.

**Comment by JeffJacobson** [comment]
I get a [missing; before statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) error in the console in Firefox Developer Edition 51.0a2 (2016-10-24) (64-bit). I've tried clearing the cache but still get the error.

**Comment by vimishor** [comment]
@julmot I can reproduce this issue in Chrome 54.0.2840.71 only if I activate [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) extension.

I get the same error as @allan-bonadio even if I disable uBlock Origin for https://bower.io and the error goes away if I completely disable uBlock Origin extension from `chrome://extensions`.

**Comment by julmot** [comment]
@sheerun The missing semicolon code is coming from `node_modules/whatwg-fetch/fetch.js` that is included with the `concat` Grunt task. The strange thing here is that the code will be included uncompressed locally, while the website shows it compressed and therefore the error happens. Do you know why?

I suspect that the minifaction is done in a network component (Cloudflare). If this is true we should move the compression to a local Grunt task to avoid this error and make sure that the code in production is equally to our local repositories. If there are other network things that may cause a different behavior to local repositories this should be documented.

**Comment by sheerun** [comment]
@julmot Sounds reasonable.

Anyone wants to prepare PR with fix? It should be as easy as properly setting linefeed setting in grunt concat: https://github.com/gruntjs/grunt-contrib-concat#separator

**Comment by julmot** [comment]
@sheerun I'll take care of this

**Comment by julmot** [comment]
The Cloudflare caching is now disabled and the issue should be solved. Can please someone else from the issue reporters try this? Thanks in advance.

**Comment by benmann** [comment]
Seems to work in FF 51.0a2 (2016-10-25) (64-bit)
