### ISSUE TITLE
Search results will be overridden by old results

### ISSUE THREAD

**Issue by julmot** [bower/bower.github.io#276]
1. Open bower.github.io/search
2. While it shows "Loading popular repositories... " type in "table"
3. The results of the search request "table" will be shown for a short time
4. The results of the initial search page, "popular repositories" will be shown ("table" results will be overriden)

=> If a search request needs more time than a newer request, the newer request will be overriden.

=> Old requests should be stopped (ignored) when new searches are requested

**Comment by sheerun** [comment]
I think it works now
