### ISSUE TITLE
keywords searching?

### ISSUE THREAD

**Issue by jas-** [bower/bower.github.io#277]
Not quite certain if this is a known issue or even by design but when searching for packages I was attempting to target a packages keywords and it didn't seem as if the web interface nor the CLI was reading that meta data.

**Comment by julmot** [comment]
Ping @andrew

**Comment by andrew** [comment]
I don't believe that the cli uses Libraries.io for search yet but if it did that would work great: https://libraries.io/search?keywords=angular&platforms=Bower

As for the web search on bower.io, it uses a prefix search on just the name to get the autocomplete-like behaviour that existed before. 

I'd recommend using the regular libraries.io search (with no autocomplete) which will enable keyword searching, the results will be very similar to: https://libraries.io/search?q=ionic&platforms=Bower&sort=

**Comment by julmot** [comment]
@andrew Thank you for the explanation!

@sheerun What do you think, should the autocomplete behavior be disabled?

**Comment by julmot** [comment]
Ping @sheerun

**Comment by sheerun** [comment]
I think we had some issue with normal autocomplete, but I don't remember what.

Probably users typed something really close to what they searched for. We could switch it, sure.

**Comment by julmot** [comment]
@sheerun Even though I've changed libraries.io API URL, I haven't added the dist files. The reason is that I'm getting a `d3 is not defined` error which would break the search entirely. Could you please be so kind and have a look at this issue in order to update the dist files?

**Comment by sheerun** [comment]
@julmot `npm install` followed by `npm run build` works for me. could you try?

**Comment by sheerun** [comment]
hmm, I see the error as well

**Comment by sheerun** [comment]
I needed to revert version changes you did in 7af13785cb5570858c800a94ccd81ec8a06973a6

**Comment by sheerun** [comment]
@andrew We get a CORS error while trying to consume libraries.io API for bower.io/seach:

> Fetch API cannot load https://libraries.io/api/search?q=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://bower.io' is therefore not allowed access. The response had HTTP status code 429. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Could you try to fix it?

**Comment by andrew** [comment]
Thats strange, CORS should be disabled for the whole API, just making dinner at the moment, will investigate later
