### ISSUE TITLE
add small example of real world use for bower install PACKAGE --save 

### ISSUE THREAD

**Issue by jstacoder** [bower/bower.github.io#279]
on the main page after 

<kbd>Create a bower.json file for your package with bower init.
Then save new dependencies to your bower.json with bower install PACKAGE --save</kbd>

would it be useful to add a line that shows why that would be helpful? ie:
<kbd>Now to distribute your new package just make sure you commit bower.json into your vcs and anyone can install all of your packages dependencies locally by simply running `bower install` </kbd>

or should something like this be included on the `creating packages` page? thoughts?

**Comment by julmot** [comment]
I don't understand what you're trying to solve. Is the doc not understandable in your opinion?

**Comment by jstacoder** [comment]
i guess i was trying to read it from a new users perspective, and doing that made me think "why would i want to do this", but i guess were not here to teach deployment practices, although it is a big part of bowers use case, so maybe it could help?

**Comment by riyadhalnur** [comment]
There's a section dedicated to creating new packages and pushing it to the registry [https://bower.io/docs/creating-packages/](https://bower.io/docs/creating-packages/)
