### ISSUE TITLE
"Error while fetching repositories" - No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by danielsu** [bower/bower.github.io#280]
Hi there,
I'm using latest Google Chrome and Google Chrome Canary and often when I search via https://bower.io/search/
bower promts me with _Sorry, there was an error while fetching repositories_

When I look in the Developer Tools I see, the cause 

> Fetch API cannot load https://libraries.io/api/search?q=angular. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://bower.io' is therefore not allowed access. The response had HTTP status code 429. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

While this might not be a direct caused by bower, it affects the frontend user experience.

**Comment by julmot** [comment]
This is related to what @sheerun mentioned in #277. We're waiting for @andrew's response

**Comment by andrew** [comment]
Investigating at the moment, it looks like there's been some change to cloudflare recently that's striping out the CORS headers as they are still working locally, will keep you updated

**Comment by andrew** [comment]
In fact, it appears to be an intermittent issue where users are hitting the unauthenticated rate limit, hence the 429 status code, which was disabled for the bower search endpoint, I'll have to investigate a way I can increase the rate limit for bower users.

**Comment by andrew** [comment]
@julmot I'm just deploying a fix to make the previous /bower-search api endpoint behave like the one you've switched to using, can you revert this commit? https://github.com/bower/bower.github.io/commit/a5687936697ff2890d02e906f461e6f5c1124572

**Comment by julmot** [comment]
@andrew Sorry to ask this but why aren't you deploying the fix to the `/search` API? Why do you need another API endpoint that behaves equivalent?

**Comment by andrew** [comment]
Because there's a rate limit on the regular search API which I've disabled for bower especially as you don't use an API key

**Comment by julmot** [comment]
Thanks @andrew!
