### ISSUE TITLE
Issues while installing bower.

### ISSUE THREAD

**Issue by sureshtv** [bower/bower.github.io#282]
I'm receiving the ETimedout message while installing bower.  Please let me know how to resolve the issue.
FYI: Am working on Virutal Desktop Image. Log details as follows:-
=====================
C:\Projects\Project.Web>bower install
bower retry         Request to https://bower.herokuapp.com/packages/sugar failed
 with ETIMEDOUT, retrying in 1.8s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 1.0s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 1.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-sani
tize failed with ETIMEDOUT, retrying in 1.1s
bower retry         Request to https://bower.herokuapp.com/packages/ngstorage fa
iled with ETIMEDOUT, retrying in 1.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-ui-r
outer failed with ETIMEDOUT, retrying in 1.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-cook
ies failed with ETIMEDOUT, retrying in 1.8s
bower retry         Request to https://bower.herokuapp.com/packages/svgxuse fail
ed with ETIMEDOUT, retrying in 1.0s
bower retry         Request to https://bower.herokuapp.com/packages/iframe-resiz
er failed with ETIMEDOUT, retrying in 1.5s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 1.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-boot
strap failed with ETIMEDOUT, retrying in 1.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 2.4s
bower retry         Request to https://bower.herokuapp.com/packages/svgxuse fail
ed with ETIMEDOUT, retrying in 2.8s
bower retry         Request to https://bower.herokuapp.com/packages/angular-sani
tize failed with ETIMEDOUT, retrying in 3.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-boot
strap failed with ETIMEDOUT, retrying in 3.5s
bower retry         Request to https://bower.herokuapp.com/packages/angular-ui-r
outer failed with ETIMEDOUT, retrying in 2.2s
bower retry         Request to https://bower.herokuapp.com/packages/iframe-resiz
er failed with ETIMEDOUT, retrying in 2.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 3.5s
bower retry         Request to https://bower.herokuapp.com/packages/ngstorage fa
iled with ETIMEDOUT, retrying in 2.9s
bower retry         Request to https://bower.herokuapp.com/packages/sugar failed
 with ETIMEDOUT, retrying in 3.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-cook
ies failed with ETIMEDOUT, retrying in 2.0s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 3.7s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 4.8s
bower retry         Request to https://bower.herokuapp.com/packages/angular-ui-r
outer failed with ETIMEDOUT, retrying in 5.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-cook
ies failed with ETIMEDOUT, retrying in 4.4s
bower retry         Request to https://bower.herokuapp.com/packages/svgxuse fail
ed with ETIMEDOUT, retrying in 4.9s
bower retry         Request to https://bower.herokuapp.com/packages/iframe-resiz
er failed with ETIMEDOUT, retrying in 6.4s
bower retry         Request to https://bower.herokuapp.com/packages/ngstorage fa
iled with ETIMEDOUT, retrying in 4.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-boot
strap failed with ETIMEDOUT, retrying in 5.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-sani
tize failed with ETIMEDOUT, retrying in 4.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 5.6s
bower retry         Request to https://bower.herokuapp.com/packages/sugar failed
 with ETIMEDOUT, retrying in 5.8s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 7.0s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 13.9s
bower retry         Request to https://bower.herokuapp.com/packages/ngstorage fa
iled with ETIMEDOUT, retrying in 13.7s
bower retry         Request to https://bower.herokuapp.com/packages/angular-cook
ies failed with ETIMEDOUT, retrying in 12.7s
bower retry         Request to https://bower.herokuapp.com/packages/svgxuse fail
ed with ETIMEDOUT, retrying in 10.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular-sani
tize failed with ETIMEDOUT, retrying in 12.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular-ui-r
outer failed with ETIMEDOUT, retrying in 14.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 14.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-boot
strap failed with ETIMEDOUT, retrying in 15.2s
bower retry         Request to https://bower.herokuapp.com/packages/sugar failed
 with ETIMEDOUT, retrying in 8.0s
bower retry         Request to https://bower.herokuapp.com/packages/iframe-resiz
er failed with ETIMEDOUT, retrying in 11.1s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 9.2s
bower retry         Request to https://bower.herokuapp.com/packages/sugar failed
 with ETIMEDOUT, retrying in 20.1s
bower retry         Request to https://bower.herokuapp.com/packages/svgxuse fail
ed with ETIMEDOUT, retrying in 27.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 22.4s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 29.0s
bower retry         Request to https://bower.herokuapp.com/packages/angular-sani
tize failed with ETIMEDOUT, retrying in 20.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-cook
ies failed with ETIMEDOUT, retrying in 22.4s
bower retry         Request to https://bower.herokuapp.com/packages/iframe-resiz
er failed with ETIMEDOUT, retrying in 24.6s
bower retry         Request to https://bower.herokuapp.com/packages/ngstorage fa
iled with ETIMEDOUT, retrying in 28.3s
bower retry         Request to https://bower.herokuapp.com/packages/angular-ui-r
outer failed with ETIMEDOUT, retrying in 16.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 28.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular-boot
strap failed with ETIMEDOUT, retrying in 30.9s
bower ETIMEDOUT     Request to https://bower.herokuapp.com/packages/sugar failed
: connect ETIMEDOUT 54.225.148.67:443

C:\Projects\Project.Web>
=====================

**Comment by jstacoder** [comment]
can your virtual desktop image connect to the internet? all the timeouts looks like a connection issue to me.

**Comment by sureshtv** [comment]
Yes, I've internet connection, no issues with that.

**Comment by sheerun** [comment]
Works for me

**Comment by sureshtv** [comment]
Please assist on my request. Thanks

**Comment by julmot** [comment]
Are you sitting behind a proxy? Does `ping google.com` work?

**Comment by sureshtv** [comment]
Yes, I'm behind proxy. 
Ping; getting timed out. But, I'm able to browse the google site and other sites, using chrome.

**Comment by julmot** [comment]
Please contact your IT. Network rules can be complex, I know that because I had similar problems. Only the  one who configured your proxy server can answer why you have network issues on the CLI.

**Comment by sureshtv** [comment]
Sure, will check with our network team and will get back on this. 
As of now, no one pointed the N/W CLI. Thanks for your support.
