### ISSUE TITLE
Hi Help needed

### ISSUE THREAD

**Issue by bazzawazza** [bower/bower.github.io#284]
Cant Install bootstrap with bower. Successfully install tether and Jquery but can't install bootstrap. Any guidance would be appreciated.

Barrys-iMac:MyPhoto barrypascoe$ bower install bootstrap
bower cached        https://github.com/twbs/bootstrap.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#*

Unable to find a suitable version for bootstrap, please choose one by typing one of the numbers below:
    1) bootstrap#^3.3.7 which resolved to 3.3.7
    2) bootstrap#v4.0.0-alpha.4 which resolved to 4.0.0-alpha.4 and is required by test

Prefix the choice with ! to persist it to bower.json

? Answer 2
Barrys-iMac:MyPhoto barrypascoe$ bower install bootstrap
bower cached        https://github.com/twbs/bootstrap.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#*

**Comment by bazzawazza** [comment]
Sorted...............

**Comment by kunyan** [comment]
Not sure what's your problem it is.

Have you installed jquery v4 before install bootstrap ? it would be have some warning about dependencies conflicts

**Comment by julmot** [comment]
Please provide your entire bower.json file

**Comment by bazzawazza** [comment]
Al sorted thanks Guys

Barry
