### ISSUE TITLE
bower update auth prompt issue

### ISSUE THREAD

**Issue by 3x1l3** [bower/bower.github.io#286]
Seems that there is an issue with authenticating over HTTPS on OS X and Linux Mint. Trying to connect to bitbucket.org private repository. Its much easier to include an annotated screenshot of whats happening when I run `bower update`

![transmark_ _transmark_obey___public_html_ _git-remote-https_ _bower_manpath__sw_share_man__opt_local_share_man__applications_xampp_xamppfiles_share_man__usr_local_share_man__usr_share_man__opt_x11_share_man__applications_xcode_app_contents_](https://cloud.githubusercontent.com/assets/11435066/25447154/568a5cd4-2a71-11e7-9237-ea7bfb3aec9b.jpg)

I'm running bower version 1.8.0 and node 6.10.2.

Part of my bower.json file:
```
 "dependencies": {
        "dragdropupload": "https://bitbucket.org/tanglemediainc/dragdrop-upload.git"
    }
```

**Comment by sheerun** [comment]
We recommend now to switch to Yarn, you can do so with https://www.npmjs.com/package/bower-away
