### ISSUE TITLE
"...psst!" message lacks context, is confusing

### ISSUE THREAD

**Issue by isaaclyman** [bower/bower.github.io#288]
On visiting the site today I saw the following message in a `<div class="notification">`:

> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

While I appreciate the recommendation, I was confused by the lack of context, especially because it's very rare to see a non-deprecated open-source tool recommend one of its "competitors." Without context, this message could introduce unnecessary doubt about Bower's future and its suitability for the task. In fact, my very first question was "Wait, what's wrong with Bower all of the sudden?"

A link to [the blog](https://bower.io/blog/2016/using-bower-with-yarn/) or to [this commit](https://github.com/bower/bower.github.io/commit/12566e5b777ef4c93c525cf3d2fa35ebc9f4d2e5) would help clue the reader in as to the scope and implications of this message so that they don't spend a lot of time investigating (as I did) in order to find answers.

**Comment by jdalton** [comment]
With [npm5 released](http://blog.npmjs.org/post/161276872334/npm5-is-now-npmlatest) I kind of think recommending npm is a better route considering it's included in the common Node install (Node 8 has npm5 included) and is one less hoop to jump through.

**Comment by sheerun** [comment]
@jdalton For now Yarn is better recommendation, please see: https://github.com/bower/bower/issues/2460#issuecomment-305154892

**Comment by jdalton** [comment]
Total bummer.

**Comment by sheerun** [comment]
@jdalton On top of it in both cases there's a deal breaker when it comes to seamlessly switching from bower: ability to install repositories without package.json. Yarn seems to have it in-progress, though: https://github.com/yarnpkg/yarn/pull/2651
