### ISSUE TITLE
Bower "Satis" (bower registry or private-bower)

### ISSUE THREAD

**Issue by LucasHaddad** [bower/bower.github.io#290]
Do you know composer satis? You can specify wich versions you would like to clone when running install/update.
I was looking for something like that for bower but couldn't find it, the closest is private-bower, however it only let me clone the entirely repository and I only need one branch. Why not specify the branch in bower.json? Because I want to constinuously change it and I don't wanna have to re-write it in every single project. So I'm looking for a private-bower satis like.

**Comment by sheerun** [comment]
you actually can specify branch in bower.json e.g. `jquery/jquery#develop` if it had develop branch

**Comment by LucasHaddad** [comment]
Not what I said. I know I can do that, what I'm trying to do is exactly the opposite. Is to specify it without having to do it. So I can constinuously change the version without having to update the bower.jsons.

**Comment by sheerun** [comment]
This is not a feature Bower has, and it isn't accepting new features as it's being deprecated in favor of Yarn
