### ISSUE TITLE
Missing version number, version date, dependencies, ...

### ISSUE THREAD

**Issue by aureole82** [bower/bower.github.io#294]
I'm missing the version number, version date, dependencies at all on the https://bower.io/search/ page:
_____
![screenshot-2017-10-30 bower search bower](https://user-images.githubusercontent.com/4819891/32175112-2d68d5b4-bd84-11e7-9fe9-8bca3a5368d8.png)

**Comment by julmot** [comment]
What's your point @aureole82?

**Comment by aureole82** [comment]
I'm missing the version number, version date, dependencies so I clicked on "Help improve these docs. Open an issue or pull request." and that's it.

**Comment by sheerun** [comment]
We don't have this information in registry and adding this information would be considerable effort (we'd need to continuously scrap each package). At this point Bower is deprecated so the effort would not be appropriate, especially version information can be checked by something as simple as `bower info jquery`
