### ISSUE TITLE
Doesn't work under fakeroot

### ISSUE THREAD

**Issue by ltworf** [bower/bower.github.io#297]
```
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
```

Thanks for your very condescending error message! I am aware of how my system should work, but you aren't.

dpkg creates packages using fakeroot, so that they look like they are built by root, and uid, username and such things don't leak inside binary packages.

Your check makes all this fail, so i'm actually forced to build as root for real, so that i can switch to another user in order for bower to work.

Can you please remove this check, so that I don't need to be root to build?

Thanks.

**Comment by sheerun** [comment]
Thanks for your very condescending issue

**Comment by sheerun** [comment]
This issue should go to bower repository (I think I saw it already there).
