### ISSUE TITLE
bower get wrong

### ISSUE THREAD

**Issue by pbadax** [bower/bower.github.io#298]
Hi,

Got a problem with bower:

I have a very old project, the first time i cloned it then bower install all went well.
Then i start migrating it, a few times later, I had to delete the project.
I cloned it again (its the same, was no commit/push or anything else on our hub) but packages have changed.

the fact is, when i run bower install, packages haved definitely changes by those i tried to migrate to.

I tried to clean the caches (from bower, then from npm) but it doesn't work.

How can i absolutly reset bower on my computer ?

I'm on W10

What i tried to reset:
bower cache clean
npm uninstall -g bower
npm cache clean --force

deleting appdata\local\bower
deleting appdata\local\conf\ the two bower related files 
deleting appdata\local\Temp\*

I also uninstalled and then installed npm.

I'll take any idea you have

**Comment by sheerun** [comment]
bower doesn't have package lock so your dependencies have changed. the only solution is to migrate to Yarn with bower-away and manually set proper package versions that were present at the time your project still worked.
