### ISSUE TITLE
Multiple repositories

### ISSUE THREAD

**Issue by dcarrasco07** [bower/bower.github.io#299]
Hi I've tried the code below (using different URLs) for multiple registries on my .bowerrc but when doing a bower install, bower only searches in the first registry declared. My bower version is 1.8.4
"registry": {
    "search": [
      "http://localhost:8000",
      "https://registry.bower.io"
    ]
  }

**Comment by sheerun** [comment]
If that's still an issue, please raise it on bower/bower repository
