### ISSUE TITLE
Document extending Bower

### ISSUE THREAD

**Issue by desandro** [bower/bower.github.io#30]
Re bower/bower#886

@wibblymat and @satazor concurred that PR would be better implemented as a 'Bower plugin', but we have no documentation around what that means, or how to do it.

**Comment by pertrai1** [comment]
@desandro - Any movement that happened with this, needs to be moved, closed, etc?

**Comment by desandro** [comment]
Closing as it's unclear what we meant by extending. Let's open a new issue if someone has a good proposal.
