### ISSUE TITLE
Search Page is broken

### ISSUE THREAD

**Issue by davejtoews** [bower/bower.github.io#312]
Any search on https://bower.io/search/ results in an error state.
<img width="794" alt="Screenshot 2022-11-24 at 9 55 33 AM" src="https://user-images.githubusercontent.com/9664035/203835719-cdc6a6ab-b458-4fa8-a5f1-c28999b053c6.png">

First noticed on Wed Nov 23. Reproduced on Safari, FireFox and Chrome on macOS 13.0.1

All API requests in the to libraries.io in the network tab appear to be returning 404 errors

**Comment by injimenez** [comment]
Any updates on this? This is still showing no results

**Comment by Krakozaber** [comment]
Still not working?

**Comment by tlebon** [comment]
in case there is any confusion about this, this is the cause: https://github.com/librariesio/libraries.io/pull/2987/files
the unprotected endpoint previously used by bower is now gone. 
the fetch [here](https://github.com/bower/bower.github.io/blob/589ca5b948c553fa2e677bc8b00ac33c547b687f/js/index.js#L137) needs to be replaced with `https://libraries.io/api/search?q=${query}&api_key={API_KEY}`

**Comment by sheerun** [comment]
It should work now
