### ISSUE TITLE
Home page recommends using vite but when clicking on how to migrate it references yarn

### ISSUE THREAD

**Issue by jasekiw** [bower/bower.github.io#313]
I'm not sure why vite is being recommended as a replacement for bower as it solves a different problem than a package manager does.
I don't know if this was typo or intentional since the steps to migrate discuss migrating to yarn, not vite.

![image](https://user-images.githubusercontent.com/4037224/213536203-93ec4a54-f7ba-4db3-b5a6-132774fc8aad.png)
![image](https://user-images.githubusercontent.com/4037224/213537156-a7ef1cbe-35f3-47d3-b6be-e695f74571c7.png)

**Comment by sheerun** [comment]
We recommend both, thank you for noticing
