### ISSUE TITLE
document how bower install <package> also installs packages from bower.json

### ISSUE THREAD

**Issue by desandro** [bower/bower.github.io#40]
from bower/bower#1352

> When I specify an endpoint, I want that installed with its dependencies, and nothing else, specifically I don't want the [bower.json] project dependencies installed.

**Comment by pertrai1** [comment]
@desandro - are the docs up to date or do we need to add more information?

**Comment by desandro** [comment]
Closing as this issue has been quiet for over a year.

**Comment by jzaefferer** [comment]
Quiet, sure, but still unresolved. There's nothing here: http://bower.io/docs/api/#install

**Comment by sheerun** [comment]
@jzaefferer I've clarified it in docs. Hope it's fine now.
