### ISSUE TITLE
SSL certificate for bower.io & subdomains

### ISSUE THREAD

**Issue by rayshan** [bower/bower.github.io#45]
Would like to see the team's appetite to make things a little more secure. We can get a free cert from StartSSL, however it only allows 1 subdomain. We may need at least:
- `stats.bower.io`
- `search.bower.io` (if we decide to move things to be more consistent, see https://github.com/bower/search/issues/37)
- `api.bower.io` (to be built, currently lives under `stats.bower.io/api/`, see https://github.com/bower/stats.bower.io/issues/2)

Also maybe this can be used for the CLI tool as well?

![https-all-the-things-300x225](https://cloud.githubusercontent.com/assets/3760840/3424108/e1213caa-ffbd-11e3-944b-7704f1b04f4f.jpg)

**Comment by cedced19** [comment]
If Github Pages doesn't support SSL, why this isssue is still open?
