### ISSUE TITLE
Hope to be able to support multiple language environment

### ISSUE THREAD

**Issue by zswang** [bower/bower.github.io#50]
Provide a directory structure, volunteers will participate in.

Thanks.

请考虑支持多语言环境
----

只要提供目录结构即可，有自愿者会参与的。

感谢。

제 목록 구조 하 면 되 는 자원 봉사자 들이 참여 할 한 다.

감사 드 린 다.

**Comment by faceleg** [comment]
@desandro @sheerun is now a good time to resurrect this? I've seen a massive upsurge in the Chinese community on Github  - this would be a good one to start with, no?

@zswang 你为什么关？我们觉得这问题很重要

**Comment by desandro** [comment]
Definitely worth considering, but for now, I feel our main priority is to keep our English docs up to date. I feel there's stuff in there that's hard to read, or out-dated

**Comment by sheerun** [comment]
I'm also not sure if we want to merge without someone dedicated for Chinese translations..

**Comment by faceleg** [comment]
You definitely need someone native in Chinese and conversant in English.
