### ISSUE TITLE
A new doc section for production use

### ISSUE THREAD

**Issue by rayshan** [bower/bower.github.io#61]
Pages are getting long...

Title suggestion: Use in production / Production use / DevOps?

Content:
- Move CI section from API
- CLI `--quiet` flag
- Analytics
- Running a private registry (docker / db replication / etc.)

Relevant issues:
https://github.com/bower/bower/issues/1455
https://github.com/bower/registry/issues/42
https://github.com/bower/registry/issues/73#issuecomment-49502055

cc @benschwarz

**Comment by pertrai1** [comment]
@desandro - Is this still relevant or should it be closed?

**Comment by desandro** [comment]
Closing. We've got most stuff [documented in API](http://bower.io/docs/api/)
