### ISSUE TITLE
Bitbucket package not listed on bower.io

### ISSUE THREAD

**Issue by efolio** [bower/bower.github.io#88]
Hi,

I published a package on bower months ago, and it still doen't show up in the website's list…
The project is hosted on Bitbucket : https://bitbucket.org/lsystems/angular-extend-promises

The repository works fine, and the install via bower too, so I think it is correctly registered.

I have no clue why it doesn't show up on bower.io though…

Thank you in advance for your help!

**Comment by davidjbradshaw** [comment]
The web search does not support bitbucket.

See: https://github.com/bower/search-server/blob/b8750d2bd34476c1d27ae64e6eab6642f9970ecc/component-list.js#L78

**Comment by sheerun** [comment]
That's true. Currently bower supports crawling only GitHub repositories.

You can send PR to add also BitBucket.
